# Generated by Django 4.1.3 on 2022-11-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='type',
        ),
    ]
